spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.2.124/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell

wechat:
  #微信公众号id
  mpAppId: wxe9ef2df5e786b62a
  mpAppSecret: c973a39ce5d2638e95f251a893cdfac4
  mchId: 4321723277
  mchKey: aDW56m05JF952rZ9UOJQ4V3PE88qQ755
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://yunfeng.ngrok.xiaomiqiu.cn/sell/pay/notify
